version: '3'
services:
  elasticsearch:
    image: qnib/plain-elasticsearch:5.5.1
    environment:
      ES_HEAP_MAX: "512m"
      ES_HEAP_MIN: "512m"
      ES_NODE_MASTER: "true"
      ES_NODE_DATA: "true"
    ports:
      - "9200:9200"
    volumes:
      - /var/lib/elasticsearch
  kibana:
    image: qnib/plain-kibana5:5.5.1
    ports:
      - "5601:5601"
    environment:
        ES_MASTER_HOST: tasks.elasticsearch
  rsyslog:
    image: qnib/alplain-rsyslog:test
    environment:
     - FORWARD_TO_ELASTICSEARCH=true
#  alpine:
#    image: qnib/alplain-init
#    environment:
#     - LOGNAME=alpine
#    command: wait.sh
#  ubuntu:
#    image: qnib/alplain-init
#    environment:
#     - LOGNAME=ubuntu
#    command: wait.sh
